### ISSUE TITLE
Update To essential 3.x (mysql => couchDb)

### ISSUE THREAD

**Issue by Xtrem65** [boermansjo/es_weashop#1]
Hi, as you probably know, essential mod 3.x is now out and includes several big changes (including used database).

CouchDB replaces mySQL.

Have you planned to update this mod too ?

Thanks,
(Keep up the good work).

**Comment by boermansjo** [comment]
I will look into this.
I will update the forum when the new version is finished.

**Comment by xchopin** [comment]
@Xtrem65 each time I am looking for some repositories, I see your question (which is copied and pasted tbh).
We are on github I mean, if you need to convert 20 plugins it should be better to learn couchDB instead of asking every authors, don't you think ?

**Comment by Xtrem65** [comment]
Thank you for judging me. It hurts... :-1: 

What bothers you with me copy-pasting the same question in different repos?
It's literally the **same question**. Why should I rephrase it ?

I asked many authors in order to : 
 - Let them know that their code is not compatible with the latest version. 
 - Ask if they are planning to update (or not)

Authors will decide wether they want to upgrade to couchDB or not. 
I don't want to fork and maintain 20 plugins (if authors don't want to upgrade to couch). And I don't have enough spare time to convert them tbh.

As you can see i'm not pushing anyone to do it. It's also a way to see if people are willing to follow kanersps to couchDB.

**Comment by boermansjo** [comment]
For now, I will not update this to couchDB. I don't want to get into all the non relational database stuff.
